version: 2
models:
    - name: 'Mod_urls'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
    - name: 'Mod_Group1'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
    - name: 'Mod_test1'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
sources:
    - name: 'main_dbt'
      schema: 'dbt'
      tables:
          - name: 'urls'