version: 2
models:
    - name: 'urls'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
    - name: 'New'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
          - name: 'Host'
            description: 'TODO: Description'
            tests: []
    - name: 'urlss'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
          - name: 'Host'
            description: 'TODO: Description'
            tests: []
sources:
    - name: 'main_dbt'
      schema: 'dbt'
      tables:
          - name: 'urls'