version: 2
models:
    - name: 'Node11'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
    - name: 'Node21'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
    - name: 'Node12'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
    - name: 'Node22'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
    - name: 'Node3'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
    - name: 'Node4'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
    - name: 'Node5'
      description: 'TODO: Description'
      columns:
          - name: 'id'
            description: 'TODO: Description'
            tests: []
          - name: 'url'
            description: 'TODO: Description'
            tests: []
          - name: 'upperurlcolumn'
            description: 'TODO: Description'
            tests: []
sources:
    - name: 'main_dbt'
      schema: 'dbt'
      tables:
          - name: 'urls'
          - name: 'urls3'